const productTypes = {
  FETCH_PRODUCTS_START: 'FETCH_PRODUCT_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCT_FAILURE',
};

export default productTypes;
