const singleProductTypes = {
  FETCH_SINGLE_PRODUCT_START: 'FETCH_SINGLE_PRODUCT_START',
  FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS',
  FETCH_SINGLE_PRODUCT_FAILURE: 'FETCH_SINGLE_PRODUCT_FAILURE',
};

export default singleProductTypes;
